import { Inter, Single_Day, Signika_Negative } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const singleDay = Signika_Negative({ weight: '400', subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>  
      <html lang="en">
        <body className={singleDay.className}>
          {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
